name: Deploy To Azure
on: [push]
env:
  AZURE_WEBAPP_NAME: CPSC481    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '481\ Portfolio/CookingInstructor/'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.100'           # set this to the dot net version to use


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:

      # Checkout the repo
      - uses: actions/checkout@main
      
      # Setup .NET Core SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      - name: Build Site
        run: dotnet publish --output output

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "output"
          output_location: ''
          skip_app_build: true
